import { AUTH_PERMISSIONS } from '@/features/auth/constants/permissions.constants';
import { USER_PERMISSIONS } from '@/features/users/constants/permissions.constants';
import type { Permission, Role } from './models';

const ALL_USER_PERMISSIONS = Object.values(USER_PERMISSIONS);
const ALL_AUTH_PERMISSIONS = Object.values(AUTH_PERMISSIONS);

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: [...ALL_USER_PERMISSIONS, ...ALL_AUTH_PERMISSIONS],
  POWER_ADMIN: [
    USER_PERMISSIONS.USER_READ,
    USER_PERMISSIONS.USER_CREATE,
    USER_PERMISSIONS.USER_UPDATE,
    USER_PERMISSIONS.USER_EXPORT,
    USER_PERMISSIONS.USER_REPORTS_VIEW,
    AUTH_PERMISSIONS.PROFILE_READ,
    AUTH_PERMISSIONS.PROFILE_UPDATE,
    AUTH_PERMISSIONS.SETTINGS_READ,
    AUTH_PERMISSIONS.SETTINGS_UPDATE,
    AUTH_PERMISSIONS.ADMIN_DASHBOARD,
  ],
  MANAGER: [
    USER_PERMISSIONS.USER_READ,
    USER_PERMISSIONS.USER_UPDATE,
    USER_PERMISSIONS.USER_REPORTS_VIEW,
    AUTH_PERMISSIONS.PROFILE_READ,
    AUTH_PERMISSIONS.PROFILE_UPDATE,
    AUTH_PERMISSIONS.SETTINGS_READ,
    AUTH_PERMISSIONS.SETTINGS_UPDATE,
  ],
  NORMAL_USER: [
    AUTH_PERMISSIONS.PROFILE_READ,
    AUTH_PERMISSIONS.PROFILE_UPDATE,
    AUTH_PERMISSIONS.SETTINGS_READ,
    AUTH_PERMISSIONS.SETTINGS_UPDATE,
  ],
  USER: [
    AUTH_PERMISSIONS.PROFILE_READ,
    AUTH_PERMISSIONS.PROFILE_UPDATE,
    AUTH_PERMISSIONS.SETTINGS_READ,
    AUTH_PERMISSIONS.SETTINGS_UPDATE,
  ],
};

export const getPermissionsForRole = (role?: Role | string | null): Permission[] => {
  if (!role) return [];
  return ROLE_PERMISSIONS[role] ?? [];
};
